CREATE TABLE public.user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    refetch_token TEXT,
    role SMALLINT DEFAULT 10 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);


ALTER TABLE public.user
ADD COLUMN phone TEXT;

ALTER TABLE "user" ADD CONSTRAINT unique_email UNIQUE ("email");
ALTER TABLE "user" ALTER COLUMN "password" DROP NOT NULL;
